### ISSUE TITLE
Incorrect Title Text For Postbit Link

### ISSUE THREAD

**Issue by WildcardSearch** [MattRogowski/Goodbye-Spammer#3]
Currently, if two users who fit the criteria for a gbs link in postbit are in the same thread page, the first is correctly titled, but the second refers to the first user in the title text.

To reproduce, start a new thread with a < 10 post account (user1) and then reply to the thread with another < 10 post account (user2). The title text for user1 will be correct, but user2 will have the following title text: `Use Goodbye Spammer on user1`.

The problem is that `$lang->load()` does not work for multiple loads of the same language file (because it uses `require_once`) and `$lang->goodbyespammer_profile` once written to the first user's name stays the same for any further gbs targets in the thread.

Will submit a pull request.

**Comment by MattRogowski** [comment]
Sorry I never fixed this @WildcardSearch, appreciate the pull request

**Comment by WildcardSearch** [comment]
No problem. I know how it is.
